# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-22 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_1', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='genre',
            new_name='batas_pendaftaran',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='jenis_lomba',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='nama_lomba',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_logo',
            new_name='poster_lomba',
        ),
    ]
