# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-22 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_1', '0003_auto_20180922_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='publisher_lomba',
            field=models.CharField(default='Organization', max_length=500),
        ),
    ]
