# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-22 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_1', '0004_album_publisher_lomba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='poster_lomba',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='publisher_lomba',
            field=models.CharField(default='', max_length=500),
        ),
    ]
